[project]
name = "visualizer-uv-venv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "argparse>=1.4.0",
    "f90nml>=1.5",
    "matplotlib>=3.10.7",
    "numpy>=2.3.3",
    "scipy>=1.16.2",
]
